[tool.black]
line-length = 88
target-version = ['py311']
exclude = '''
/(
    \.git
  | \.github
  | \.pytest_cache
  | \.vscode
  | \.venv
  | api/migrations
  | satenv
  | nginx
  | docs
  | test.py
  | test2.py
)/
'''

[tool.ruff]
lint.select = ["E", "F", "I", "N", "UP", "S", "B"]
src = ["src"]

[tool.towncrier]
directory = "src/api/changes"
package_dir = "src"
version = "1.2.1"
filename = "changes.md"
