[tool.black]
line-length = 88
target-version = ['py311']
exclude = '''
/(
    \.git
  | \.github
  | \.pytest_cache
  | \.vscode
  | \.venv
  | api/migrations
  | satenv
  | nginx
  | docs
  | test.py
  | test2.py
)/
'''

[tool.ruff]
lint.select = ["E", "F", "I", "N", "UP", "S", "B"]
src = ["src"]

[tool.mypy]
mypy_path = "src"

python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = true
warn_unreachable = true
warn_unused_ignores = true
warn_redundant_casts = true
explicit_package_bases = true

exclude = [
  'api/migrations',
  'docs',
  'examples',
  'tests',
  'env',
  'data',
]


[[tool.mypy.overrides]]
module = ["flask.*", "sqlalchemy.*", "celery.*", "redis.*", "astropy.*", "flasgger.*", "flask_apscheduler.*", 'flask_migrate.*', 'requests.*', 'skyfield.*', 'sgp4.*']
ignore_missing_imports = true

[tool.towncrier]
directory = "src/api/changes"
package_dir = "src"
filename = "changes.md"
issue_format = "[#{issue}](https://github.com/iausathub/satchecker/pull/{issue})"

[[tool.towncrier.type]]
directory = "misc"
name = "Miscellaneous"
showcontent = true  # This ensures full content is shown

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bugfixes"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "Improved Documentation"
showcontent = true

[[tool.towncrier.type]]
directory = "removal"
name = "Deprecations and Removals"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = "Features"
showcontent = true

[[tool.towncrier.type]]
directory = "changed"
name = "Changes"
showcontent = true
