"""add S3 file link and run id

Revision ID: 345fd9dd1e6d
Revises: 47a6b948f843
Create Date: 2026-06-23 14:50:02.156337

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "345fd9dd1e6d"
down_revision = "47a6b948f843"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interpolable_ephemeris",
        sa.Column("parquet_points_file", sa.Text(), nullable=True),
    )
    op.add_column(
        "interpolable_ephemeris",
        sa.Column("run_id", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interpolable_ephemeris", "run_id")
    op.drop_column("interpolable_ephemeris", "parquet_points_file")
    # ### end Alembic commands ###
