FROM --platform=linux/amd64 docker.io/python:3.11-slim

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH /usr/src/app
ENV SKYFIELD_DATA_DIR=/app/skyfield-data
ENV ASTROPY_SITES_JSON=/app/astropy-data/sites.json
ENV ASTROPY_CACHE_DIR=/tmp/astropy_cache
ENV SERVICE_NAME=celery

RUN apt-get update && apt-get install -y curl \
    && pip install --upgrade pip \
    && mkdir -p /app/skyfield-data /app/astropy-data \
    && curl -sL -o /app/skyfield-data/de430t.bsp \
    https://ssd.jpl.nasa.gov/ftp/eph/planets/bsp/de430t.bsp \
    && curl -sL -o /app/astropy-data/sites.json \
    https://www.astropy.org/astropy-data/coordinates/sites.json \
    && apt-get remove -y curl && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . ./api
RUN celery --version
CMD ["celery", "-A", "api.satchecker.celery", "worker", "--loglevel=info", "--concurrency=8"]
