name: Performance Benchmark
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/api/requirements.txt
          pip install pytest pytest-benchmark

      # Run benchmark with pytest-benchmark and store the output
      - name: Run benchmark
        run: |
          python -m pytest --benchmark-only --benchmark-json output.json || true
          # keep going even if some tests fail

      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        if: always() # Run even if the benchmark tests have some failures
        with:
          tool: 'pytest'
          output-file-path: output.json
          # previous run info
          external-data-json-path: ./cache/benchmark-data.json
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: dev/bench
          # Access token to deploy GitHub Pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          # Workflow will fail when an alert happens
          fail-on-alert: true
          # Enable alert commit comment
          comment-on-alert: false
          # Mention @username if benchmark alert happens
          # alert-comment-cc-users: '@yourusername
