# This workflow will run code coverage and add a comment to the pull request

name: Code coverage - pull request

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_satchecker
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r src/api/requirements.txt
    - name: Install dependencies
      run: |
        pip install pytest pytest-mock pytest-cov
    - name: Create test database
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -c 'DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_database WHERE datname = '\''test_satchecker'\'') THEN CREATE DATABASE test_satchecker; END IF; END $$;'
    - name: Start Flask application
      run: |
        export FLASK_APP=satchecker.py
        flask run &
      working-directory: src/api
    - name: Run Celery worker
      run: |
          celery -A api.satchecker.celery worker --loglevel INFO &
      env:
          REDIS_URL: redis://localhost:6379/0
      working-directory: src
    - name: Test with pytest
      run: |
        pytest --ignore=tests/benchmark --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=. --cov-config=pytest.ini tests/ | tee pytest-coverage.txt
      env:
        REDIS_URL: redis://localhost:6379/0
        PYTHONPATH: src
        SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@localhost:5432/test_satchecker
        LOCAL_DB: 1
    - name: Pytest coverage comment
      id: coverageComment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
