name: EthicalCheck-Workflow

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Trigger_EthicalCheck:
    permissions:
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download OpenAPI Specification
        run: curl -o apispec.json https://dev.satchecker.cps.iau.noirlab.edu/apispec.json

      - name: Validate JSON Syntax
        run: jq empty apispec.json

      - name: EthicalCheck Free & Automated API Security Testing Service
        uses: apisec-inc/ethicalcheck-action@005fac321dd843682b1af6b72f30caaf9952c641
        with:
          oas-url: "apispec.json"
          email: ${{ secrets.ETHICALCHECK_EMAIL }}
          sarif-result-file: "ethicalcheck-results.sarif"

      - name: Upload SARIF file to repository
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./ethicalcheck-results.sarif
